name: Build and Release

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Fix tsconfig.json
              run: |
                  sed -i '/"esModuleInterop"/d' node_modules/@tsconfig/svelte/tsconfig.json
                  sed -i '/"verbatimModuleSyntax"/d' node_modules/@tsconfig/svelte/tsconfig.json
                  sed -i '/"moduleResolution"/c\    "moduleResolution": "node",' node_modules/@tsconfig/svelte/tsconfig.json

            - name: Build
              id: build
              run: bun run build

            # Create the release on GitHub
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  name: ${{ github.ref_name }}
                  tag_name: ${{ github.ref }}
                  files: |
                      dist/main.js
                      dist/manifest.json
                      dist/styles.css
